const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
const menuButton = document.querySelector('.menu-toggle');
const mobileNav = document.querySelector('#mobile-nav');
function closeMenu(){menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open navigation');mobileNav.hidden=true;document.body.classList.remove('menu-open');document.querySelector('main').inert=false;}
menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close navigation':'Open navigation');mobileNav.hidden=!open;document.body.classList.toggle('menu-open',open);document.querySelector('main').inert=open});
document.querySelectorAll('#mobile-nav a,.header a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobileNav.hidden){closeMenu();menuButton.focus()}});
window.matchMedia('(min-width:641px)').addEventListener('change',e=>{if(e.matches)closeMenu()});
function updateTime(){document.querySelector('#local-time').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Karachi',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())+' PKT'}updateTime();setInterval(updateTime,60000);

// A lightweight, pointer-responsive mathematical field; no 3D dependencies.
const canvas=document.querySelector('#field');const ctx=canvas.getContext('2d');let w=0,h=0,angle=0,frame,visible=true,last=0;let pointer={x:0,y:0},target={x:0,y:0};
function resize(){const rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw(0)}
function project(x,y,z){let ry=angle*.24+pointer.x*.22;let rx=.5+pointer.y*.18;const xx=x*Math.cos(ry)+z*Math.sin(ry);const zz=-x*Math.sin(ry)+z*Math.cos(ry);const yy=y*Math.cos(rx)-zz*Math.sin(rx);const z2=y*Math.sin(rx)+zz*Math.cos(rx);let s=680/(680+z2);return{x:w*.52+xx*s,y:h*.49+yy*s,z:z2}}
function draw(t){ctx.clearRect(0,0,w,h);const r=Math.min(w*.31,h*.34);for(let j=0;j<34;j++){const u=j/34*Math.PI*2;ctx.beginPath();for(let i=0;i<=110;i++){let v=i/110*Math.PI*2;let rr=r*(1+.31*Math.cos(v));let p=project(rr*Math.cos(u),r*.43*Math.sin(v),rr*Math.sin(u));if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.strokeStyle='rgba(172,209,111,.32)';ctx.lineWidth=.65;ctx.stroke()}for(let j=0;j<22;j++){const v=j/22*Math.PI*2;ctx.beginPath();for(let i=0;i<=120;i++){const u=i/120*Math.PI*2;let rr=r*(1+.31*Math.cos(v));let p=project(rr*Math.cos(u),r*.43*Math.sin(v),rr*Math.sin(u));if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.strokeStyle='rgba(187,222,138,.31)';ctx.lineWidth=.6;ctx.stroke()}const p=project(r*1.31,0,0);ctx.fillStyle='#c6fa5f';ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();}
function loop(t){if(t-last>32){angle+=.009;pointer.x+=(target.x-pointer.x)*.04;pointer.y+=(target.y-pointer.y)*.04;draw(t);last=t}if(visible&&!document.hidden&&!reducedMotion.matches)frame=requestAnimationFrame(loop)}
function start(){cancelAnimationFrame(frame);if(visible&&!document.hidden&&!reducedMotion.matches)frame=requestAnimationFrame(loop);else draw(0)}
document.querySelector('.hero').addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){const rect=canvas.getBoundingClientRect();target.x=(e.clientX-rect.left)/w-.5;target.y=(e.clientY-rect.top)/h-.5}});
new ResizeObserver(resize).observe(canvas);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;start()}).observe(canvas);document.addEventListener('visibilitychange',start);reducedMotion.addEventListener('change',start);

const projects={bdoto:{name:'BD OTO',type:'Business development automation',intro:'A business development platform that keeps prospect activity, reporting, and notifications connected.',items:['Automated prospect tracking and reporting for business development activity.','Configurable notifications to keep stakeholders across regions informed.','Integrated AI automation workflows to streamline routine tasks and support reporting.'],focus:'Automation · AI workflows · Business systems'},playground:{name:'AI Playground',type:'AI-assisted proposal development',intro:'An AI-powered workspace that helps turn requirements into high-level business proposals.',items:['Built a workspace for creating structured proposal drafts from user requirements.','Supported a review-and-refine workflow so people stay in control of the final proposal.'],focus:'Generative AI · Product development · Proposal workflows'}};
const dialog=document.querySelector('#project-dialog');
projects.pubq={name:'PubQ',type:'Connected food-service platform',intro:'A platform for ordering, payments, and reporting across app, web, kiosk, and point of sale.',heading:'The product',items:['Connects guest ordering with payment and kitchen fulfilment.','Brings menu management and operational reporting together across sales channels.','Serves contract catering, restaurants, and event operations.'],focus:'Multi-channel commerce · Ordering & payments · Food-service operations',url:'https://pubq.se/',note:'Product overview based on pubq.se. This ecosystem study is an original portfolio illustration, not a production screenshot.'};
Object.assign(projects,{vehicle:{name:'FleetSense',type:'Ride-hailing & predictive analytics',intro:'A vehicle management platform connecting ride-hailing workflows, operational reporting, and maintenance planning.',items:['Developed ride-hailing workflows and operational reporting.','Integrated AI-based repair-cost predictions to identify vehicles likely to incur higher maintenance spending relative to their value.','Supported repair prioritization and budget planning with predictive insights.'],focus:'Ride-hailing · Predictive analytics · Operational reporting'},cau:{name:'CAU',type:'Financial operations',intro:'A centralized platform for connected financial workflows.',items:['Centralized accounting, reporting, budgeting, and forecasting workflows.','Automated manual tasks across financial operations.'],focus:'Accounting · Budgeting · Forecasting · Automation'},skillstitute:{name:'Skillstitute',type:'E-learning',intro:'Course-based learning with assessment built into the experience.',items:['Delivered course-based learning modules.','Integrated quizzes so learners could assess their knowledge within each module.'],focus:'E-learning · Course delivery · Integrated assessment'}});
document.addEventListener('click',e=>{const card=e.target.closest('[data-project]');if(!card)return;const p=projects[card.dataset.project];if(!p)return;document.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">${p.type}</p><h2 id="dialog-title">${p.name}</h2><p>${p.intro}</p><h3>${p.heading || 'My contribution'}</h3><ul>${p.items.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Focus</h3><p>${p.focus}</p>${p.url ? `<a class="text-link" href="${p.url}" target="_blank" rel="noopener noreferrer">Visit ${p.name}<span aria-hidden="true">↗</span></a>` : ''}<p class="dialog-note">${p.note || (p.name === 'FleetSense' ? 'FleetSense is the portfolio title for the Vehicle Management System described in my résumé. ' : '') + 'Project details are based on my professional experience. Portfolio visuals are illustrative studies, not production screenshots.'}</p>`;dialog.showModal();document.body.style.overflow='hidden'});
function closeDialog(){dialog.close();document.body.style.overflow=''}document.querySelector('.close-dialog').addEventListener('click',closeDialog);dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
document.querySelector('#year').textContent=new Date().getFullYear();
const agentStages={
 retrieve:{kicker:'CONTEXT BEFORE COMPLETION',title:'Find the signal.<br>Leave the noise.',description:'Embeddings and vector databases surface relevant knowledge by meaning. Retrieval-augmented generation brings that context into the model’s response.',tags:['Vector databases','Embeddings','Semantic search','RAG'],flow:['A question + knowledge sources','Embed → retrieve → rank','Relevant context with sources']},
 reason:{kicker:'TURN INTENT INTO A PLAN',title:'A clear goal.<br>A considered next step.',description:'An agent needs a defined task, useful context, and bounded decisions. Break the work into steps, choose appropriate tools, and return structured outputs.',tags:['AI agents','Task planning','Structured outputs','Context management'],flow:['User intent + retrieved context','Plan → select tools → validate inputs','A bounded next action']},
 act:{kicker:'CONNECT INTELLIGENCE TO TOOLS',title:'Move from an answer<br>to an action.',description:'Model Context Protocol gives AI applications a standard way to connect to tools and context. Tool calling turns a plan into an explicit operation, with permissions and human review where needed.',tags:['MCP','Tool calling','API integration','Human review'],flow:['A validated plan + permitted tools','Discover → call → inspect result','A tool result the agent can use']},
 evaluate:{kicker:'CLOSE THE FEEDBACK LOOP',title:'Useful is good.<br>Verifiable is better.',description:'Check outputs against the task, inspect failures, and keep a trace of tool activity. Evaluation and observability make it possible to improve a workflow instead of guessing.',tags:['Evaluations','Observability','Guardrails','Feedback loops'],flow:['Output + execution trace','Check quality → inspect failures','A reviewed result + improvement signals']}
};
const agentTabs=[...document.querySelectorAll('[data-stage]')];
function activateStage(button){const key=button.dataset.stage;const s=agentStages[key];const index=agentTabs.indexOf(button);agentTabs.forEach(tab=>{const active=tab===button;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1});const panel=document.querySelector('#agent-panel');panel.setAttribute('aria-labelledby',button.id);panel.innerHTML=`<div><p class="agent-kicker">${s.kicker}</p><h3>${s.title}</h3><p class="agent-description">${s.description}</p><div class="agent-tags">${s.tags.map(tag=>`<span>${tag}</span>`).join('')}</div></div><div class="agent-trace"><div class="trace-heading"><span>ILLUSTRATIVE FLOW</span><span>0${index+1} / 04</span></div><ol>${s.flow.map((text,i)=>`<li><span>${['INPUT','PROCESS','OUTPUT'][i]}</span><strong>${text}</strong></li>`).join('')}</ol></div>`;}
agentTabs.forEach((button,index)=>{button.addEventListener('click',()=>activateStage(button));button.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(index+1)%agentTabs.length;else if(e.key==='ArrowLeft')next=(index+agentTabs.length-1)%agentTabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=agentTabs.length-1;if(next!==undefined){e.preventDefault();activateStage(agentTabs[next]);agentTabs[next].focus()}})});
if(!reducedMotion.matches){document.documentElement.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.pubq-feature,.project,.project-row,.about-layout,.about-stats,.expertise-layout,.intelligence-heading,.agent-lab,.experience-list,.contact-heading').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
